# Generated by Django 5.1.5 on 2025-03-11 16:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('cycle_length', models.SmallIntegerField()),
                ('period_length', models.SmallIntegerField()),
                ('last_period_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CyclePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(choices=[('M, Menstrual', 'Menstrual'), ('F, Follicular', 'Follicular'), ('O, Ovulation', 'Ovulation'), ('L, Luteal', 'Luteal')], max_length=50)),
                ('description', models.TextField(validators=[django.core.validators.MinValueValidator(100, message='Enter at least 100 words!')])),
            ],
        ),
        migrations.CreateModel(
            name='CyclePhaseOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.cyclecalendar')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.cyclephase')),
            ],
        ),
    ]
