# Generated by Django 5.2.1 on 2025-07-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='banner',
            field=models.ImageField(default=1, upload_to='section-images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('SIM', 'Self Improvement'), ('WAM', 'Work and Money'), ('STY', 'Style')], max_length=50),
        ),
    ]
