# Generated by Django 5.2.1 on 2025-07-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('self-improvement', 'Self Improvement'), ('work-and-money', 'Work and Money'), ('style', 'Style')], max_length=50),
        ),
    ]
