# Generated by Django 5.2.1 on 2025-06-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(blank=True, choices=[('Happy', 'Happy'), ('In Period', 'In Period'), ('Calm', 'Calm'), ('Angry', 'Angry'), ('Heartbroken', 'Heartbroken')], max_length=50, unique=True)),
                ('reminder', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/images/moods/')),
            ],
        ),
    ]
