# Generated by Django 5.2.1 on 2025-07-02 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(blank=True, choices=[('Happy', 'Happy'), ('In Period', 'In Period'), ('Calm', 'Calm'), ('Angry', 'Angry'), ('Heartbroken', 'Heartbroken')], default='Calm', max_length=50, unique=True)),
                ('reminder', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='mood-images/')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('mood', models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='diary.moods')),
            ],
        ),
    ]
