# Generated by Django 5.2.1 on 2025-06-23 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='mood',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='diary.moods'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='moods',
            name='mood',
            field=models.CharField(blank=True, choices=[('Happy', 'Happy'), ('In Period', 'In Period'), ('Calm', 'Calm'), ('Angry', 'Angry'), ('Heartbroken', 'Heartbroken')], default='Calm', max_length=50, unique=True),
        ),
    ]
