# Generated by Django 5.2.1 on 2025-07-08 21:10

from django.db import migrations


def create_moods(apps, schema_editor):
    MoodsModel = apps.get_model('diary', 'Moods')

    moods = [
        {
            "mood": "Happy",
            "reminder": "Stay present in your joy — you're glowing for a reason!",
            "image": "moods/happy.png"
        },
        {
            "mood": "Angry",
            "reminder": "It’s okay to feel this. Breathe deeply and respond, not react.",
            "image": "moods/anger.png"
        },
        {
            "mood": "In Period",
            "reminder": "Take it easy today. Rest, hydrate, and honor your body.",
            "image": "moods/in_period.png"
        },
        {
            "mood": "Calm",
            "reminder": "Protect your peace — you’ve earned this calm.",
            "image": "moods/calm.png"
        },
        {
            "mood": "Heartbroken",
            "reminder": "Healing takes time. Let yourself feel and trust that better days are coming.",
            "image": "moods/heartbroken.png"
        },
    ]

    for mood in moods:
        MoodsModel.get_or_create(
            name=mood['mood'],
            defaults={
                'reminder': mood['reminder'],
                'image': mood['image']
            }
        )

def reverse_moods_creation(apps, schema_editor):
    MoodsModel = apps.get_model('diary', 'Moods')

    moods_to_delete = ["Happy", "Angry", "In Period", "Calm", "Heartbroken"]

    MoodsModel.objects.filter(mood__in=moods_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=create_moods,
            reverse_code=reverse_moods_creation
        )
    ]
