# Generated by Django 5.2.1 on 2025-07-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_period_date', models.DateField()),
                ('cycle_length', models.PositiveSmallIntegerField(default=28)),
                ('period_length', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='CyclePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(choices=[('M', 'Menstrual'), ('F', 'Follicular'), ('O', 'Ovulation'), ('L', 'Luteal')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
