# Generated by Django 5.1.5 on 2025-03-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CyclePhaseOccurrence',
        ),
    ]
