# Generated by Django 5.2.1 on 2025-06-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_delete_cyclephaseoccurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_length', models.PositiveSmallIntegerField(default=28)),
                ('period_length', models.PositiveSmallIntegerField(default=5)),
                ('last_period_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('content', models.TextField()),
                ('mood_choices', models.CharField(blank=True, choices=[('HappyHappy', 'Happy'), ('CalmCalm', 'Calm'), ('ConfidentConfident', 'Confident'), ('GratefulGrateful', 'Grateful'), ('OptimisticOptimistic', 'Optimistic'), ('SadSad', 'Sad'), ('InsecureInsecure', 'Insecure'), ('TiredTired', 'Tired'), ('AnxiousAnxious', 'Anxious'), ('IrritableIrritable', 'Irritable'), ('Excited', 'Excited'), ('Lonely', 'Lonely'), ('Overwhelmed', 'Overwhelmed'), ('Peaceful', 'Peaceful'), ('Motivated', 'Motivated'), ('Bored', 'Bored'), ('Stressed', 'Stressed'), ('Hopeful', 'Hopeful'), ('Jealous', 'Jealous'), ('Content', 'Content'), ('Frustrated', 'Frustrated'), ('Nostalgic', 'Nostalgic'), ('Guilty', 'Guilty'), ('Relieved', 'Relieved'), ('Embarrassed', 'Embarrassed'), ('Curious', 'Curious'), ('Inspired', 'Inspired'), ('Apathetic', 'Apathetic'), ('Shy', 'Shy'), ('Proud', 'Proud')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CycleCalendar',
        ),
        migrations.AlterField(
            model_name='cyclephase',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cyclephase',
            name='phase_name',
            field=models.CharField(choices=[('M', 'Menstrual'), ('F', 'Follicular'), ('O', 'Ovulation'), ('L', 'Luteal')], max_length=50),
        ),
    ]
