# Generated by Django 5.2.1 on 2025-07-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_nutritionplan_trainingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='recovery_tips',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='workout_tips',
            field=models.JSONField(default=list),
        ),
    ]
