# Generated by Django 5.2.1 on 2025-06-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0003_cycleprofile_diary_delete_cyclecalendar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(blank=True, choices=[('1', 'Happy'), ('2', 'In Period'), ('3', 'Calm'), ('4', 'Angry'), ('5', 'Heartbroken')], max_length=50, unique=True)),
                ('reminder', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='diary',
            name='mood_choices',
        ),
    ]
