# Generated by Django 5.2.1 on 2025-06-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0004_moods_remove_diary_mood_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='moods',
            name='image',
            field=models.ImageField(default=1, upload_to='moods/'),
            preserve_default=False,
        ),
    ]
