# Generated by Django 5.2.1 on 2025-06-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0005_moods_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moods',
            name='mood',
            field=models.CharField(blank=True, choices=[('Happy', 'Happy'), ('In Period', 'In Period'), ('Calm', 'Calm'), ('Angry', 'Angry'), ('Heartbroken', 'Heartbroken')], max_length=50, unique=True),
        ),
    ]
